CREATE DATABASE DB_FACULDADE;
USE DB_FACULDADE;

CREATE TABLE TBL_PROFESSOR(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_PROFESSOR VARCHAR(500),
CPF CHAR(11),
DT_NASC DATE NOT NULL,
DT_ADMISSAO TIMESTAMP DEFAULT NOW(),
FL_ATIVO CHAR(1) DEFAULT 'S',
EMAIL VARCHAR(150),
NUM_TELEFONE CHAR(11),

CONSTRAINT UQ_PROFESSOR_CPF UNIQUE (CPF),
CONSTRAINT UQ_PROFESSOR_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE TBL_ALUNO(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_ALUNO VARCHAR(500),
CPF CHAR(11),
DT_NASC DATE NOT NULL,
DT_ADMISSAO TIMESTAMP DEFAULT NOW(),
FL_ATIVO CHAR(1) DEFAULT 'S',
EMAIL VARCHAR(150),
NUM_TELEFONE CHAR(11),

CONSTRAINT UQ_ALUNO_CPF UNIQUE (CPF),
CONSTRAINT UQ_ALUNO_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE TBL_TIPO_GRADUACAO(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_GRADUACAO VARCHAR(100),
DESCRICAO TEXT

);

CREATE TABLE TBL_CURSO(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_CURSO VARCHAR(200),
ID_GRADUACAO INT,
DESCRICAO TEXT,
FL_ATIVO CHAR(1) DEFAULT 'S',

CONSTRAINT FK_GRADUACAO FOREIGN KEY (ID_GRADUACAO) REFERENCES TBL_TIPO_GRADUACAO(ID)
);

CREATE TABLE TBL_TURMA_CURSO(
ID INT AUTO_INCREMENT PRIMARY KEY,
ID_CURSO INT,
DT_INICIO DATE,
DT_FIM DATE,
FL_ATIVO CHAR(1) DEFAULT 'S',

CONSTRAINT FK_CURSO FOREIGN KEY (ID_CURSO) REFERENCES TBL_CURSO(ID)
);

CREATE TABLE TBL_MATRICULA(
ID INT AUTO_INCREMENT PRIMARY KEY,
ID_TURMA_CURSO INT,
ID_ALUNO INT,
FL_ATIVO CHAR(1) DEFAULT 'S',

CONSTRAINT FK_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES TBL_ALUNO(ID),
CONSTRAINT FK_TURMA FOREIGN KEY (ID_TURMA_CURSO) REFERENCES TBL_TURMA_CURSO(ID)
);

CREATE TABLE TBL_MATERIAS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_MATERIA VARCHAR(200),
DESCRICAO TEXT,
OBRIGATORIO CHAR(1) DEFAULT 'S',
FL_ATIVO CHAR(1) DEFAULT 'S'

);

CREATE TABLE TBL_MATERIA_CURSO(
ID INT AUTO_INCREMENT PRIMARY KEY,
ID_CURSO INT,
ID_MATERIA INT,
FL_ATIVO CHAR(1) DEFAULT 'S',
DS_SEMESTRE INT,

CONSTRAINT FK_CURSO_MATERIA FOREIGN KEY (ID_CURSO) REFERENCES TBL_CURSO(ID),
CONSTRAINT FK_MATERIA_CURSO FOREIGN KEY (ID_MATERIA) REFERENCES TBL_MATERIAS(ID)
);

CREATE TABLE TBL_PROFESSOR_MATERIA_CURSO(
ID INT AUTO_INCREMENT PRIMARY KEY,
ID_PROFESSOR INT,
ID_MATERIA_CURSO INT,
FL_ATIVO CHAR(1) DEFAULT 'S',

CONSTRAINT FK_PROFESSOR_MATERIA FOREIGN KEY (ID_PROFESSOR) REFERENCES TBL_PROFESSOR(ID),
CONSTRAINT FK_MATERIA_CURSO_PROFESSOR FOREIGN KEY (ID_MATERIA_CURSO) REFERENCES TBL_MATERIA_CURSO(ID)
);

CREATE TABLE TBL_NOTAS(
ID INT AUTO_INCREMENT PRIMARY KEY,
ID_MATRICULA INT,
ID_MATERIA_CURSO INT,
NOTA_FINAL DECIMAL (5,2),

FOREIGN KEY (ID_MATRICULA) REFERENCES TBL_MATRICULA(ID),
FOREIGN KEY (ID_MATERIA_CURSO) REFERENCES TBL_MATERIA_CURSO(ID),
UNIQUE(ID_MATRICULA, ID_MATERIA_CURSO)
);

INSERT INTO TBL_TIPO_GRADUACAO (NOME_GRADUACAO, DESCRICAO) VALUES
('Tecnólogo', 'Curso superior de curta duração com foco prático'),
('Bacharelado', 'Curso superior com formação ampla e teórica'),
('Licenciatura', 'Curso superior voltado à formação de professores');

INSERT INTO TBL_CURSO (NOME_CURSO, ID_GRADUACAO, DESCRICAO) VALUES
('Análise e Desenvolvimento de Sistemas', 1, 'Curso focado em programação e desenvolvimento de software'),
('Engenharia de Software', 2, 'Curso para formar engenheiros de software'),
('Matemática - Licenciatura', 3, 'Formação para professores de matemática');

INSERT INTO TBL_TURMA_CURSO (ID_CURSO, DT_INICIO, DT_FIM) VALUES
(1, '2025-02-01', '2027-12-01'), -- Turma de ADS
(2, '2025-02-01', '2029-12-01'), -- Turma de Engenharia
(3, '2025-02-01', '2028-12-01'); -- Turma de Matemática

INSERT INTO TBL_MATERIAS (NOME_MATERIA, DESCRICAO, OBRIGATORIO) VALUES
('Algoritmos', 'Introdução à lógica de programação', 'S'),
('Banco de Dados', 'Modelagem e SQL', 'S'),
('Engenharia de Requisitos', 'Levantamento de requisitos', 'S'),
('Didática', 'Técnicas de ensino', 'N');

INSERT INTO TBL_MATERIA_CURSO (ID_CURSO, ID_MATERIA, DS_SEMESTRE) VALUES
(1, 1, 1), -- ADS → Algoritmos (1º semestre)
(1, 2, 2), -- ADS → Banco de Dados (2º semestre)
(2, 1, 1), -- Engenharia → Algoritmos (1º semestre)
(2, 2, 2), -- Engenharia → Banco de Dados (2º semestre)
(2, 3, 3), -- Engenharia → Eng. Requisitos (3º semestre)
(3, 4, 1); -- Matemática → Didática (1º semestre)

INSERT INTO TBL_PROFESSOR (NOME_PROFESSOR, CPF, DT_NASC, EMAIL, NUM_TELEFONE) VALUES
('Carlos Mendes', '11111111111', '1980-05-10', 'carlos.mendes@facul.com', '11999999999'),
('Ana Ribeiro', '22222222222', '1985-08-15', 'ana.ribeiro@facul.com', '21988888888'),
('João Silva',  '33333333333', '1975-12-22', 'joao.silva@facul.com',  '31977777777');

-- Pegando IDs gerados automaticamente
-- Carlos → Algoritmos ADS + Banco de Dados ADS
INSERT INTO TBL_PROFESSOR_MATERIA_CURSO (ID_PROFESSOR, ID_MATERIA_CURSO) VALUES
(1, 1), -- Carlos dá Algoritmos em ADS
(1, 2), -- Carlos dá Banco de Dados em ADS
(2, 4), -- Ana dá Banco de Dados em Engenharia
(2, 5), -- Ana dá Eng. Requisitos em Engenharia
(3, 6); -- João dá Didática em Matemática

INSERT INTO TBL_ALUNO (NOME_ALUNO, CPF, DT_NASC, EMAIL, NUM_TELEFONE) VALUES
('Pedro Souza', '44444444444', '2000-03-12', 'pedro.souza@email.com', '11966666666'),
('Mariana Lima', '55555555555', '2001-07-25', 'mariana.lima@email.com', '21955555555'),
('Rafael Costa', '66666666666', '1999-11-08', 'rafael.costa@email.com', '31944444444');

-- Pedro e Mariana em ADS
INSERT INTO TBL_MATRICULA (ID_TURMA_CURSO, ID_ALUNO) VALUES
(1, 1),
(1, 2),
-- Rafael em Engenharia
(2, 3);

-- Pedro em Algoritmos ADS
INSERT INTO TBL_NOTAS (ID_MATRICULA, ID_MATERIA_CURSO, NOTA_FINAL) VALUES
(1, 1, 8.5), -- Pedro → Algoritmos ADS
(1, 2, 9.0), -- Pedro → Banco de Dados ADS
(2, 1, 7.0), -- Mariana → Algoritmos ADS
(3, 3, 8.0); -- Rafael → Algoritmos Engenharia

SELECT 
A.NOME_ALUNO, F.NOME_CURSO AS NOME_CURSO, G.NOME_MATERIA, D.NOTA_FINAL FROM TBL_ALUNO A
INNER JOIN TBL_MATRICULA B ON A.ID = B.ID_ALUNO
INNER JOIN TBL_TURMA_CURSO C ON B.ID_TURMA_CURSO = C.ID
INNER JOIN TBL_NOTAS D ON D.ID_MATRICULA = B.ID
INNER JOIN TBL_MATERIA_CURSO E ON D.ID_MATERIA_CURSO = E.ID
INNER JOIN TBL_CURSO F ON E.ID_CURSO = F.ID
INNER JOIN TBL_MATERIAS G ON E.ID_MATERIA = G.ID;

SELECT * FROM TBL_ALUNO;

-- DROP DATABASE DB_FACULDADE;


