CREATE DATABASE DB_MERCADO;
USE DB_MERCADO;

CREATE TABLE TBL_CLIENTE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100),
	CPF CHAR(11) UNIQUE,
	NUM_TELEFONE CHAR(11),
	EMAIL VARCHAR(100) UNIQUE,
	FL_ATIVO CHAR(1)
);

CREATE TABLE TBL_COLABORADOR(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100),
	CPF CHAR(11) UNIQUE,
	NUM_TELEFONE CHAR(11),
	EMAIL VARCHAR(100) UNIQUE,
	FL_ATIVO CHAR(1),
    DT_ADMISSAO TIMESTAMP DEFAULT NOW(),
    DT_NASCIMENTO DATE
);

CREATE TABLE TBL_VENDAS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_COLABORADOR INT,
    ID_CLIENTE INT,
    DT_COMPRA TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (ID_COLABORADOR) REFERENCES TBL_COLABORADOR(ID),
	FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTE(ID)
    
);

CREATE TABLE TBL_PRODUTOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    COD_BARRAS CHAR(13) UNIQUE, #NUMERO PADRÃO DO EAN-13 PARA CODIGO DE BARRAS
	NOME VARCHAR(100),
	FL_ATIVO CHAR(1),
	DT_INSERCAO TIMESTAMP DEFAULT NOW()

);

CREATE TABLE TBL_VIGENCIA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_PRODUTO INT,
	DT_VIGENCIA DATETIME NOT NULL,
	DT_VALIDADE DATETIME NOT NULL,
	PRECO_UNIT FLOAT,
	FL_ATIVO CHAR(1),

	FOREIGN KEY (ID_PRODUTO) REFERENCES TBL_PRODUTOS(ID)

);

CREATE TABLE TBL_VENDA_PRODUTOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_VENDA INT,
	ID_PRODUTO INT,
	DT_INSERCAO TIMESTAMP DEFAULT NOW(),
	QUANTIDADE INT,
    PRECO_UNIT FLOAT,
	FOREIGN KEY (ID_VENDA) REFERENCES TBL_VENDAS(ID),
	FOREIGN KEY (ID_PRODUTO) REFERENCES TBL_PRODUTOS(ID)

);

CREATE TABLE TBL_PAGAMENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_VENDA INT,
    TIPO_PAGAMENTO ENUM('DINHEIRO', 'CARTAO', 'PIX', 'VALE_ALIMENTACAO'),
    VALOR_PAGO FLOAT,
    FOREIGN KEY (ID_VENDA) REFERENCES TBL_VENDAS(ID)
);

drop database db_mercado;